### ISSUE TITLE
Too good to be true...

### ISSUE THREAD

**Issue by Zexyp** [stepankarlovec/stepankarlovec.github.io#1]
As your class m8 I have to say you can do a bit more next time.
It's awful to see you lay your ass whole day.

**Comment by stepankarlovec** [comment]
hey dont be rude!!!!! We have friendly community over here so! First of all u should use my pronouns!! - Nick/her !!!! Stop bullyin’ me all the time.. not everybody can code in JSfuck… but dont worry i’ll learn how to code in html and i will hack you with html u c# loser hahahahhahahaa take the L bozo
